URL_SERVICE = "https://cnt-7d380f61-108e-4e50-99f7-728126dc1af9.containerhub.tripleten-services.com/"
DOC_PATH = "/docs/"
LOG_MAIN_PATH = "/api/logs/main/"
USERS_TABLE_PATH = "/api/db/resources/user_model.csv"
CREATE_USER_PATH = "/api/v1/users/"
PRODUCTS_KITS_PATH = "/api/v1/products/kits"